### ISSUE TITLE
Crash in UWP Release mode

### ISSUE THREAD

**Issue by bugadani** [rotorgames/Rg.Plugins.Popup#110]
Using Xamarin Forms 2.3.5-pre1 (not sure about older releases) and Release mode, pushing a page using PushPopupAsync fails with the following exception:

"Unhandled exception at 0x06AD46D3 (Windows.UI.Xaml.dll) in <app name>.UWP.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x120340B8, 0x00000006)."

-		base	{System.NullReferenceException: Arg_NullReferenceException
   at Rg.Plugins.Popup.Services.PopupNavigation.PushAsync(PopupPage page, Boolean animate)
   at <namespace>.ViewModels.MeasureViewModel.<<-ctor>b__78_2>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__9_0(Object state) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 971
   at System.Action`1.Invoke(T obj)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Threading\SynchronizationContext.cs:line 170}	System.Exception {System.NullReferenceException}

Visual Studio stops in SharedStubs.g.cs which is a generated code file, in the following method:
		// Signature, Windows.UI.Core.DispatchedHandler.Invoke, [rev] [return] [Mcg.CodeGen.ComHRESULTReturnMarshaller] void__int, 

As a side note, code is working fine in Debug configuration

**Comment by bugadani** [comment]
After more investigation, it looks like this issue is related to .Net Native compilation. The code that calls PushPopAsync is the following:

            SelectDeviceCommand = new Command(
                async () =>
                {
                    if (_popupOpen)
                    {
                        return;
                    }
                    _popupOpen = true;
                    var deviceSelectorPage = new DeviceSelectorPage(this);
                    deviceSelectorPage.Disappearing += SelectorDisappearing;
                    await AbortMeasurement();
                    await Navigation.PushPopupAsync(deviceSelectorPage);
                },
                () => !IsConnected);

**Comment by rotorgames** [comment]
@bugadani Did you see it? 

https://github.com/rotorgames/Rg.Plugins.Popup#uwp-example

**Comment by bugadani** [comment]
Apparentally, I missed it. Thank you!
