### ISSUE TITLE
Crash open popup multiple times

### ISSUE THREAD

**Issue by sirfilipef** [rotorgames/Rg.Plugins.Popup#131]
Hello im having a trouble with a crash happening when i open a popup multiple times.
I have a button that opens a popup, if i press that button multiple times the error belong happens.
I think this happens in Android and iOS. Im using **1.1.0-pre2**.

```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
  at android.view.ViewGroup.addViewInner(ViewGroup.java:4310)
  at android.view.ViewGroup.addView(ViewGroup.java:4146)
  at android.view.ViewGroup.addView(ViewGroup.java:4087)
  at android.view.ViewGroup.addView(ViewGroup.java:4060)
  at mono.java.lang.RunnableImplementor.n_run(RunnableImplementor.java:-2)
  at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5435)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by rotorgames** [comment]
@sirfilipef Hi. You can't open one instance of page secondary!

**Comment by avorobjovs** [comment]
@rotorgames , I think you mean it is not eligible to open the same page instance twice. 

But it's definitely possible. On a device, you can have time to tap on a button twice or triple before a command will be handled. In such case, two or three instances of a page will be opened. 

In case, if this page is based on the Rg.Plugins.Popup, then several instances of the same Rg.Plugins.Popup is opened and the application crashes.

Could you please add some protection in your code to prevent an opening of several instances of the Rg.Plugins.Popup pages?

**Comment by avorobjovs** [comment]
I have the same bug
`
Java.Lang.RuntimeException: The specified child already has a parent. You must call removeView() on the child's parent first.
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e9637fd961864a4bb2189bf3cb5bcd02>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <a77ebce94ba54f59b98d609bdfa061d9>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <a77ebce94ba54f59b98d609bdfa061d9>:0 
  at Android.Views.ViewGroup.AddView (Android.Views.View child) [0x00031] in <be5349914b4d467bbd469cf364959264>:0 
  at Rg.Plugins.Popup.Droid.Impl.PopupNavigationDroid.AddPopup (Rg.Plugins.Popup.Pages.PopupPage page) [0x00034] in <cf10a5a1e63740219e90aa2d1599c262>:0 
  at Rg.Plugins.Popup.Services.PopupNavigation.PushAsync (Rg.Plugins.Popup.Pages.PopupPage page, System.Boolean animate) [0x00043] in <e4a0d036d16d43a8a07fbef673df812b>:0 
  at KC.Mobility.Technician.Controls.Editors.BasePopupView`1+<>c+<<-ctor>b__16_0>d[T].MoveNext () [0x00045] in <ff1c0248b9a948859e22cb3ebbfc0a79>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e9637fd961864a4bb2189bf3cb5bcd02>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <e9637fd961864a4bb2189bf3cb5bcd02>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <be5349914b4d467bbd469cf364959264>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <be5349914b4d467bbd469cf364959264>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <be5349914b4d467bbd469cf364959264>:0 
  at (wrapper dynamic-method) System.Object:845bfade-810b-4bfb-85a6-e8248ad75252 (intptr,intptr)
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4659)
	at android.view.ViewGroup.addView(ViewGroup.java:4500)
	at android.view.ViewGroup.addView(ViewGroup.java:4440)
	at android.view.ViewGroup.addView(ViewGroup.java:4413)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onClick(Native Method)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onClick(VisualElementRenderer_1.java:74)
	at android.view.View.performClick(View.java:6261)
	at android.view.View$PerformClick.run(View.java:23748)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
`

**Comment by rotorgames** [comment]
@sirfilipef @avorobjovs Please try to use v1.1.0-preX version

**Comment by rotorgames** [comment]
I think that I resolved this problem. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

Not afraid to reopen this issue if you have this problem again.

Thanks.

**Comment by EeKay** [comment]
Just for completeness sake: I got this message because I didn't call the Init function (see https://github.com/rotorgames/Rg.Plugins.Popup/wiki/Getting-started for the details) in the Main Activity's OnCreate.
