### ISSUE TITLE
Using FormattedText on Label Crashes on UWP

### ISSUE THREAD

**Issue by EmilAlipiev** [rotorgames/Rg.Plugins.Popup#163]
I am getting very strange behaviour. I have page where I havent implemented any popup at all. When I click button on uwp on this page, my application is crashing everytime. Stacktrace show me that it crashes for this plugin and it looks like OnBackRequested is fired even on the page where there is no popup or neither on the page before I had popup. So it cant be that popup wasnt disposed because I never showed a popup. How can I solve this? any quick idea please? 

```

   at System.StubHelpers.HStringMarshaler.ConvertToNativeReference(String managed, HSTRING_HEADER* hstringHeader)
   at Windows.UI.Xaml.Documents.Run.put_Text(String value)
   at Xamarin.Forms.Platform.UWP.FormattedStringExtensions.ToRun(Span span)
   at Xamarin.Forms.Platform.UWP.LabelRenderer.UpdateText(TextBlock textBlock)
   at Xamarin.Forms.Platform.UWP.LabelRenderer.OnElementChanged(ElementChangedEventArgs`1 e)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.UWP.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.UWP.VisualElementPackager.OnChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.UWP.VisualElementPackager.Load()
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.UWP.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.UWP.VisualElementPackager.OnChildAdded(Object sender, ElementEventArgs e)
   at Xamarin.Forms.Platform.UWP.VisualElementPackager.Load()
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.SetElement(VisualElement element)
   at Xamarin.Forms.Platform.UWP.Platform.CreateRenderer(VisualElement element)
   at Xamarin.Forms.Platform.UWP.VisualElementExtensions.GetOrCreateRenderer(VisualElement self)
   at Rg.Plugins.Popup.WinPhone.Impl.PopupPlatformWinPhone.<RemoveAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rg.Plugins.Popup.Services.PopupNavigationImpl.<RemoveAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rg.Plugins.Popup.Services.PopupNavigationImpl.<RemovePageAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rg.Plugins.Popup.WinPhone.Impl.PopupPlatformWinPhone.<OnBackRequested>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at Microsoft.HockeyApp.Extensibility.Windows.UnhandledExceptionTelemetryModule.CoreApplication_UnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)
```

**Comment by EmilAlipiev** [comment]
I finally found the reason why I get error above, this is caused by FormattedText on Label in the popup. It works fine on Android Application and It works fine using Text property instead FormattedText but On UWP using FormattedText doesnt work

**Comment by rotorgames** [comment]
@EmilAlipiev Hi. Did you fix this problem?

**Comment by rotorgames** [comment]
I think that I resolved this problem. You can test it from the development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

Not afraid to reopen this issue if you have this problem again.

Thanks.
