### ISSUE TITLE
The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by JoesWeek** [rotorgames/Rg.Plugins.Popup#412]
version：1.1.5.188
log：
Xamarin Exception Stack:
Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <45b0bc0cc3534e029b7d11c24eb5b14a>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) <0xc5951738 + 0x0009b> in <45b0bc0cc3534e029b7d11c24eb5b14a>:0
  at Android.Views.ViewGroup.AddView (Android.Views.View child) <0xc5d1e538 + 0x000e7> in <68108ce9a509467e9e3fc4e6ca918e41>:0
  at Rg.Plugins.Popup.Droid.Impl.PopupPlatformDroid.AddAsync (Rg.Plugins.Popup.Pages.PopupPage page) <0xc3550a30 + 0x000ab> in <2c84bcd5850d4629957fe969f92dd4e6>:0
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<AddAsync>d__11.MoveNext () <0xc4fcd684 + 0x000e3> in <dba573e2b78848139a5467939864ff97>:0
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass7_0+<<PushAsync>b__0>d.MoveNext () <0xc4fcc550 + 0x004c3> in <dba573e2b78848139a5467939864ff97>:0
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass15_0+<<InvokeThreadSafty>b__0>d.MoveNext () [0x00067] in <dba573e2b78848139a5467939864ff97>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) <0xc62192a8 + 0x00058> in <94be0ec456b34af784b1d900e9fd4a97>:0
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () <0xc5dcee34 + 0x00017> in <68108ce9a509467e9e3fc4e6ca918e41>:0
  at Java.Lang.Thread+RunnableImplementor.Run () <0xc5e4dc38 + 0x0002f> in <68108ce9a509467e9e3fc4e6ca918e41>:0
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) <0xc5e467cc + 0x00057> in <68108ce9a509467e9e3fc4e6ca918e41>:0
  at (wrapper dynamic-method) System.Object.46(intptr,intptr)
  at java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
  at android.view.ViewGroup.addViewInner(ViewGroup.java:5099)
  at android.view.ViewGroup.addView(ViewGroup.java:4930)
  at android.view.ViewGroup.addView(ViewGroup.java:4870)
  at android.view.ViewGroup.addView(ViewGroup.java:4843)
  at mono.java.lang.RunnableImplementor.n_run(Native Method)
  at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
  at android.os.Handler.handleCallback(Handler.java:891)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:207)
  at android.app.ActivityThread.main(ActivityThread.java:7470)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by rotorgames** [comment]
Do you try to open the same page twice?

**Comment by JoesWeek** [comment]
Yes,I created a progress bar function.I modified the source code and found no problems for the time being.
```csharp
public Task AddAsync(PopupPage page)
        {
            var decoreView = DecoreView;

            page.Parent = XApplication.Current.MainPage;

            var renderer = page.GetOrCreateRenderer();
            ViewGroup p = renderer.View.Parent as ViewGroup;

            if (p != null)
            {
                p.RemoveAllViewsInLayout();
            }

            decoreView.AddView(renderer.View);

            return PostAsync(renderer.View);
        }
```

**Comment by rotorgames** [comment]
It is not good solution. In the new version whicj i'm going to publish you can't do it because there will be some checkers for it. I advise you to check PopupStack before to push a page. 
You can't push a page if there is the page in PopupStack.

**Comment by JoesWeek** [comment]
ok,I will modify it after the new version is released. thanks.
