### ISSUE TITLE
[UWP] Crash showing a PopupPage that contains a CarouselView

### ISSUE THREAD

**Issue by juanmalm** [rotorgames/Rg.Plugins.Popup#650]
## 🐛 Bug Report

Create a PopupPage that contains a Xamarin.Forms 5.0 CarouselView and push it.
Current behavior: It crashes.

```
System.ArgumentException: Delegate to an instance method cannot have null 'this'.
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at Xamarin.Forms.Platform.UWP.CarouselViewRenderer.InitialSetup(Object sender, SizeChangedEventArgs e)
```

### Expected behavior
Popup appears properly

### Reproduction steps
- Create a new PopupPage
- Add a CarouselView to previous PopupPage's xaml
- Push the PopupPage

### Configuration
Xamarin.Forms 5.0
Windows 10 19042.804

**Version:** 2.0.0.10

**Platform:** 
- [x] :earth_americas: UWP

**Comment by LuckyDucko** [comment]
hey @juanmalm does it work okay if the new popuppage already contained the carousel view? instead of adding it, I assume through the `content` property?

**Comment by juanmalm** [comment]
Hi @LuckyDucko, same behavior with the popup already containing the carousel view in its xaml.

**Comment by LuckyDucko** [comment]
Alright @juanmalm are you able to create a standalone project that demonstrates this just so we can ensure that there is nothing special in your project that may be causing the issue

**Comment by juanmalm** [comment]
Sure! Here you have @LuckyDucko 

[App5.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/6088825/App5.zip)

**Comment by LuckyDucko** [comment]
Hi @juanmalm i apologise i've been busy

So ive been going about testing this, and currently i've tracked down that it will occur once a forcelayout is applied. However, in some random circumstances, say 10% of the time, i have been able to get it working properly. It usually happened while i was using breakpoints, which makes me think there is a point where something internal is still completing while i've hit a breakpoint elsewhere?

I need to somehow be able to view whats going on within Xamarin.forms, however it isn't as easy as adding a project and tracing how it goes, as i have dropped a try/catch around many things yet it still doesn't seem to be caught until too late. 

I'm adding this comment so i know where i have gotten up to. I need to work out whats going on inside xamarin forms to decipher what we need to adjust.
